
CREATE TABLE Songs (
	Title VARCHAR(100) NOT NULL,
	Album VARCHAR(50) NOT NULL,
	Id INT NOT NULL,
	PRIMARY KEY (Id),
	FOREIGN KEY (Id) REFERENCES Moods (SId)
);

CREATE TABLE Moods (
	SId INT NOT NULL,
	Happy BOOLEAN NOT NULL,
	Sad BOOLEAN NOT NULL,
	Mad BOOLEAN NOT NULL,
	Free BOOLEAN NOT NULL,
	Confused BOOLEAN NOT NULL,
	Frustrated BOOLEAN NOT NULL,
	Regretful BOOLEAN NOT NULL,
	Nostalgic BOOLEAN NOT NULL,
	Betrayed BOOLEAN NOT NULL,
	Lonely BOOLEAN NOT NULL,
	Empowered BOOLEAN NOT NULL,
	Afraid BOOLEAN NOT NULL,
	Vengeful BOOLEAN NOT NULL,
	Sarcastic BOOLEAN NOT NULL,
	Social BOOLEAN NOT NULL,
	Hopeful BOOLEAN NOT NULL,
	Desperate BOOLEAN NOT NULL,
	Foolish BOOLEAN NOT NULL,
	Amazed BOOLEAN NOT NULL,
	Brave BOOLEAN NOT NULL,
	PRIMARY KEY (SId)
);